### ISSUE TITLE
The specified mixin 'net.fabricmc.tiny.mixin.mixins.gui.VideoOptionsScreenMixin' was not found

### ISSUE THREAD

**Issue by Madis0** [Ficklampan/TinyMod#10]
TinyMod 0.0.2b, Fabric API 0.14.1 b 372, Minecraft 1.16.1

<details>

[Info: 2020-07-18 07:36:27.157262459: client_handler.cpp(195)] Register game instance log listener using token:  3
[Info: 2020-07-18 07:36:27.420566088: GameCallbacks.cpp(158)] Game/FabricLoader (main) Info Loading for game Minecraft 1.16.1
[Info: 2020-07-18 07:36:27.716793367: GameCallbacks.cpp(158)] Game/Fabric|Loader (main) Info [FabricLoader] Loading 45 mods: minecraft@1.16.1, fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-screen-handler-api-v1@1.0.1+f362c86e02, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, fabric-keybindings-v0@0.2.0+3fa9f7c502, modmenu@1.14.5+build.30, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.8+5ce5339802, fabricloader@0.9.0+build.204, fabric-tool-attribute-api-v1@1.1.4+5794386e02, fabric-renderer-indigo@0.3.2+4d66bed502, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.5+e00ecb5f02, fabric-dimensions-v1@1.0.0+a71b305302, fabric-biomes-v1@0.2.7+059ea86602, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, cotton-client-commands@1.0.1+1.16-rc1, fabric-api-base@0.1.3+12a8474c02, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.0+e16a977402, cloth-config2@4.6.0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-resource-loader-v0@0.2.6+f41e209802, fabric-textures-v0@1.0.4+eae12eb802, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-rendering-fluids-v1@0.1.8+b7084faa02, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.0.0+b0993bc102, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, fabric-loot-tables-v1@0.1.10+059ea86602, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, tiny@0.0.2, fabric@0.14.1+build.372-1.16, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-models-v0@0.1.0+dfdb52d602, fabric-item-groups-v0@0.2.0+438f963602, fabric-object-builders-v0@0.6.0+da175ad602, fabric-networking-v0@0.1.10+e00ecb5f02
[Info: 2020-07-18 07:36:27.766241308: GameCallbacks.cpp(158)] Game/mixin (main) Info SpongePowered MIXIN Subsystem Version=0.8 Source=file:/home/username/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[Info: 2020-07-18 07:36:28.032495200: GameCallbacks.cpp(158)] Game/mixin (main) Fatal Mixin prepare failed preparing gui.VideoOptionsScreenMixin in tiny.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'net.fabricmc.tiny.mixin.mixins.gui.VideoOptionsScreenMixin' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.tiny.mixin.mixins.gui.VideoOptionsScreenMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: The specified mixin 'net.fabricmc.tiny.mixin.mixins.gui.VideoOptionsScreenMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848)
	... 15 more

[Info: 2020-07-18 07:36:28.059374151: GameCallbacks.cpp(158)] Launcher/launcher (main) Info 
Exception in thread "main" org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tiny.mixins.json:gui.VideoOptionsScreenMixin] from phase [DEFAULT] in config [tiny.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:591)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:518)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.tiny.mixin.mixins.gui.VideoOptionsScreenMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)
	... 12 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'net.fabricmc.tiny.mixin.mixins.gui.VideoOptionsScreenMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848)
	... 15 more

[Info: 2020-07-18 07:36:28.059481133: GameCallbacks.cpp(158)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code 1
[Info: 2020-07-18 07:36:28.060772782: GameController.cpp(480)] Game closed with id 3

</details>

**Comment by EdvinVikstrom** [comment]
fixed maybe  \\_O_/
edit: my emote not working so good...

**Comment by Madis0** [comment]
Yup
```
\_O_/
  |
 / \
```
